### ISSUE TITLE
Remove cancel workflow

### ISSUE THREAD

**Issue by saraedum** [echemdb/svgdigitizer#75]
the cancel.yml workflow is obsolete. Instead we should use something like this to make sure that outdated workflows don't start on GitHub:
```yaml
concurrency:
  group: doc-${{ github.ref }}
  cancel-in-progress: true
```
